language: swift
osx_image: xcode10.2
before_script: "./scripts/add-keys.sh"
after_script: "./scripts/remove-key.sh"
script:
  - "./scripts/swiftLint.sh"
  - "./scripts/buildPrebidSDK.sh"
  - "./scripts/testPrebidSDK.sh"
  - "./scripts/testPrebidDemo.sh"
